spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/Users/artjom/java/SpringBoot/route-manager/route-manager-frontend/route-manager-backend/src/main/resources/data.db;AUTO_SERVER=TRUE
    password: password
    username: user
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
